version: '3'

services:
  dogSitterdb:
    image: postgres
    container_name: dogSitterdb
    restart: always
    environment:
      - POSTGRES_USER=celeste
      - POSTGRES_PASSWORD=fullstackp3
      - POSTGRES_DB=dogSitterdb
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
   

